trigger:
- master

pr:
- master

pool:
  vmImage: 'macos-latest'

resources:
  repositories:
  - repository: templates
    type: github
    name: swellaby/azure-pipelines-templates
    endpoint: swellaby

steps:
- task: UseNode@1
  displayName: 'Use Node 16.x'
  inputs:
    version: 16.x

- template: '../steps/run-tests.yml'
  parameters:
    envName: 'Mac'
