trigger:
- master

pr:
- master

pool:
  vmImage: 'windows-latest'

resources:
  repositories:
  - repository: templates
    type: github
    name: swellaby/azure-pipelines-templates
    endpoint: swellaby

steps:
- task: UseNode@1
  displayName: 'Use Node 16.x'

- template: '../steps/run-tests.yml'
  parameters:
    envName: 'Windows'
